apiVersion: v1
kind: Secret
metadata:
  name: '{{ template "stolon.fullname" . }}'
  labels:
    name: '{{ template "stolon.fullname" . }}'
    {{- include "stolon.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ template "application.password" . }}
  replpassword: {{ template "replication.password" . }}
  {{- if .Values.standby.enabled }}
  standbypassword: {{ template "standby.passwordfile.content" . }}
  {{- end }}
