{{- if .Values.metrics.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: '{{ template "stolon.fullname" . }}'
  labels:
    name: {{ template "stolon.fullname" . }}-servicemonitor
    {{- include "stolon.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ template "exporter.fullname" .}}
      release: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.scrapeInterval }}
{{- end -}}