apiVersion: v1
kind: Service
metadata:
  name: {{ include "stolon.fullname" . }}
  labels:
    name: {{ template "stolon.fullname" . }}
    {{- include "stolon.labels" . | nindent 4 }}
spec:
  selector:
    stolon-proxy: "true"
    stolon-cluster: {{ template "stolonctl.clustername" . }}
  ports:
    - port: 5432
