apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ template "sentinel.fullname" . }}'
  labels:
    name: '{{ template "sentinel.fullname" . }}'
    {{- include "stolon.labels" . | nindent 4 }}
spec:
  {{- $backend := include "store.backend" . }}
  replicas: {{.Values.stolon.sentinel.replicas}}
  selector:
    matchLabels:
      name: {{ template "sentinel.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "sentinel.fullname" . }}
        {{- include "stolon.selectorLabels" . | nindent 8 }}
        component: stolon-sentinel
        stolon-cluster: {{ template "stolonctl.clustername" . }}
    spec:
      {{- if eq $backend "kubernetes" }}
      serviceAccountName: '{{template "stolon.fullname" .}}-stolon'
      serviceAccount: '{{template "stolon.fullname" .}}-stolon'
      {{- end }}
      {{- if ne $backend "kubernetes" }}
      initContainers:
        - name: wait-for-store
          image: jwilder/dockerize
          command: ['dockerize', '-timeout', '120s', '-wait', '{{ template "store.backend.healthURL" . }}']
      {{- end }}
      containers:
      - name: {{ template "sentinel.fullname" . }}
        image: '{{- .Values.stolon.image.name -}}:{{- .Values.stolon.image.tag -}}'
        imagePullPolicy: {{ .Values.stolon.image.pullPolicy }}
        command:
          - "/bin/bash"
          - "-ec"
          - |
            exec gosu stolon stolon-sentinel
        env:
          - name: STSENTINEL_DEBUG
            value: "{{- .Values.stolon.sentinel.debug -}}"
          - name: STSENTINEL_CLUSTER_NAME
            value: {{ template "stolonctl.clustername" . }}
          - name: STOLONCTL_CLUSTER_NAME
            value: $(STSENTINEL_CLUSTER_NAME)
          - name: STSENTINEL_STORE_BACKEND
            value: {{ $backend }}
          - name: STOLONCTL_STORE_BACKEND
            value: $(STSENTINEL_STORE_BACKEND)
          {{- if eq $backend "kubernetes" }}
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: STSENTINEL_KUBE_RESOURCE_KIND
            value: configmap
          - name: STOLONCTL_KUBE_RESOURCE_KIND
            value: $(STSENTINEL_KUBE_RESOURCE_KIND)
          - name: STOLONCTL_KUBE_NAMESPACE
            value: {{ .Release.Namespace }}
          {{- else }}
          - name: STSENTINEL_STORE_ENDPOINTS
            value: {{ template "store.endpoint" . }}
          - name: STOLONCTL_STORE_ENDPOINTS
            value: $(STSENTINEL_STORE_ENDPOINTS)
          {{- end }}
        resources:
{{ toYaml .Values.stolon.sentinel.resources | indent 10 }}
