apiVersion: v1
kind: Service
metadata:
  name: '{{ template "postgresql.standby.fullname" . }}'
  labels:
{{- include "postgresql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
{{- include "postgresql.labels" . | nindent 4 }}
    role: standby