apiVersion: v1
kind: Secret
metadata:
  name: pgconf-postgresql
  labels:
    app: postgresql
    release: "pgconf"
type: Opaque
data:
  postgres-password: c29tZS1yYW5kb20tcGFzc3dvcmQ=
  postgres-replication-password: "cmVwbC1wYXNzd29yZA=="
