apiVersion: v1
kind: Service
metadata:
  name: pgconf-postgresql
  labels:
    app: postgresql
    release: "pgconf"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
    app: postgresql
    release: "pgconf"
    role: primary